### ISSUE TITLE
Multiple POI in the same location

### ISSUE THREAD

**Issue by absempere** [tezcatlipoca/maptool#5]
I can't access multiple points in the same location, only the most recent. A way to scroll, to expand, or to use search and click on a result to pop it to the front?

**Comment by tezcatlipoca** [comment]
Added markercluster for support for this, but it conflicts with drag and drop for repositioning POI. For now I've changed "lock" so it just applies to poi and turns off the clustering, let's see how that goes and open a new issue if it's not working.
